name: Deploy
on: [push]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update -y && sudo apt-get install -y asciidoctor
    - run: make all
  deploy:
    name: "Deploy to netlify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y && sudo apt-get install -y asciidoctor
      - run: make all
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_TOKEN_AUTH: ${{ secrets.NETLIFY_TOKEN_AUTH }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist
          NETLIFY_DEPLOY_TO_PROD: true
